version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel git python python-json5
      - run:
          name: Unit Test
          command: |
            PYTHONPATH=$PYTHONPATH:. python securedrop/tests/client_test.py
            PYTHONPATH=$PYTHONPATH:. python securedrop/tests/command_test.py
