version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel git python python-json5
      - run:
          name: Unit Test
          command: |
            PYTHONPATH=$PYTHONPATH:. python securedrop/tests/registration_test.py
            bash scripts/keygen.sh < scripts/key_test_input_server.txt
