version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm python python-pycryptodome python-tornado
      - run:
          name: Unit Test
          command: ./scripts/test.sh
