version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel git python python-json5
      - run:
          name: Unit Test
          command: |
            cd securedrop/tests
            python registration_test.py
