version: 2

jobs:
  build:
    docker:
      - image: archlinux
    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel git python python-json5
      - run:
          name: Install pip
          command: pacman -S --noconfirm python-pip
      - run:
           name: Install pycryptodome
           command: pip install pycryptodome
      - run:
          name: Unit Test
          command: |
            PYTHONPATH=$PYTHONPATH:. python securedrop/tests/client_test.py
            PYTHONPATH=$PYTHONPATH:. python securedrop/tests/command_test.py
            PYTHONPATH=$PYTHONPATH:. python securedrop/tests/encrypt_test.py
