version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel git python python-json5 python-pycryptodome python-tornado python-email-validator
      - run:
          name: Unit Test
          command: ./scripts/test.sh
