version: 2

jobs:
  build:
    docker:
      - image: alpine:edge

    steps:
      - checkout
      - run:
          name: Install required tools
          command: |
            apk add --no-cache bash python3 py3-tornado py3-pycryptodome py3-email-validator openssl py3-yapf py3-pip
            pip install nest-asyncio
      - run:
          name: Formatting
          command: ./scripts/format.sh check
      - run:
          name: Unit Test
          command: ./scripts/test.sh
